name: Maven Build and Release

on:
  # Trigger the workflow on push to main or version tags
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Triggers on tags that look like v1.0.0, v1.1.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build with Maven
      - name: Build with Maven
        run: mvn -B clean install

      # Step 5: Run tests
      - name: Run tests
        run: mvn test

      # Step 6: Create GitHub Release (only on tags)
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar  # Include your built jar file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
