name: Maven Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Trigger on tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build with Maven
      - name: Build with Maven
        run: mvn -B clean install

      # Step 5: Run tests
      - name: Run tests
        run: mvn test

      # Step 6: List target directory (debugging step)
      - name: List target directory
        run: ls -la target/

      # Step 7: Debugging - Print GitHub Ref
      - name: Debugging - Print GitHub Ref
        run: echo "GitHub Ref: ${{ github.ref }}"

  release:
    if: startsWith(github.ref, 'refs/tags/')  # Correctly placed at the job level
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar  # Upload built jar to the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
