name: Maven Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Trigger on tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build with Maven
      - name: Build with Maven
        run: mvn -B clean install

      # Step 5: Run tests
      - name: Run tests
        run: mvn test

      # Step 6: Upload JAR file as an artifact
      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: keycloak-group-membership-uuid-mapper
          path: target/keycloak-group-membership-uuid-mapper-*.jar  # Use your appropriate pattern

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Download the JAR file artifact
      - name: Download JAR file artifact
        uses: actions/download-artifact@v3
        with:
          name: keycloak-group-membership-uuid-mapper

      # Step 3: Create GitHub Release (conditional based on a tag push)
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: keycloak-group-membership-uuid-mapper
          files: keycloak-group-membership-uuid-mapper-*.jar  # Use your appropriate pattern
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
